// <auto-generated />
using System;
using Luthn.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luthn.Core.Persistence.Persistence.Migrations
{
    [DbContext(typeof(LuthnDbContext))]
    [Migration("20260812142856_AddExpiringSensitiveTurnSummaryReferences")]
    partial class AddExpiringSensitiveTurnSummaryReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Luthn.Core.Persistence.AgentConnectionChannelRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ActivityState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConfigurationOwner")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConnectorVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntegrationKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessfulActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "UpdatedAt");

                    b.HasIndex("WorkspaceId", "AgentId", "Channel")
                        .IsUnique();

                    b.ToTable("agent_connection_channels", null, t =>
                        {
                            t.HasCheckConstraint("CK_agent_connection_channels_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_agent_connection_channels_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.AuditEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("system");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("unspecified");

                    b.Property<string>("PayloadClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PayloadVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("RedactionState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Workspace");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasDefaultValue("default");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "OccurredAt");

                    b.HasIndex("WorkspaceId", "CorrelationId");

                    b.HasIndex("ScopeKind", "WorkspaceId", "OccurredAt");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_audit_events_scope_workspace", "(\"ScopeKind\" = 'Workspace' AND \"WorkspaceId\" <> '') OR (\"ScopeKind\" = 'Installation' AND \"WorkspaceId\" = '')");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.ClassificationResultRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StorageDecision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.ToTable("classification_results", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.CollectionProvenanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorTrust")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AuthenticatedActor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AuthenticatedUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClaimedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClaimsTrust")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ConnectorVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ContractVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("MemoryItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PluginId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("MemoryItemId")
                        .IsUnique();

                    b.HasIndex("SourceEventId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ReceivedAt");

                    b.ToTable("collection_provenance", null, t =>
                        {
                            t.HasCheckConstraint("CK_collection_provenance_authenticated_user_id", "\"AuthenticatedUserId\" <> ''");

                            t.HasCheckConstraint("CK_collection_provenance_subject", "\"SourceEventId\" IS NOT NULL OR \"MemoryItemId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_collection_provenance_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.HubIngressQueueRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentConnectionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("CapsuleSizeBytes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MemberUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedCapsule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectionScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Sensitivity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageDecision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "State", "AcceptedAt");

                    b.HasIndex("State", "NextAttemptAt", "AcceptedAt");

                    b.HasIndex("WorkspaceId", "AgentConnectionId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "AgentId", "AcceptedAt");

                    b.HasIndex("WorkspaceId", "MemberUserId", "AcceptedAt");

                    b.HasIndex("WorkspaceId", "State", "AcceptedAt");

                    b.ToTable("hub_ingress_queue", null, t =>
                        {
                            t.HasCheckConstraint("CK_hub_ingress_queue_capsule_size", "\"CapsuleSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_hub_ingress_queue_member_user_id", "\"MemberUserId\" <> ''");

                            t.HasCheckConstraint("CK_hub_ingress_queue_organization_id", "\"OrganizationId\" <> ''");

                            t.HasCheckConstraint("CK_hub_ingress_queue_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.LocalInstallationStateRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("OriginInstanceId")
                        .IsUnique();

                    b.ToTable("local_installation_state", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SafeProjectionSyncCheckpointRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TransportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Checkpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkspaceId", "TransportName");

                    b.ToTable("safe_projection_sync_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_safe_projection_sync_checkpoints_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SafeProjectionSyncOutboxRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LocalRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OriginInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemoteCheckpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("SafeEnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt", "CreatedAt");

                    b.HasIndex("WorkspaceId", "State", "CreatedAt");

                    b.HasIndex("WorkspaceId", "OriginInstanceId", "LocalRecordId", "Revision", "Operation")
                        .IsUnique();

                    b.ToTable("safe_projection_sync_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_safe_projection_sync_outbox_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_safe_projection_sync_outbox_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessDecisionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PayloadClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RedactionState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SensitiveAccessRequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SensitiveAccessRequestId");

                    b.ToTable("sensitive_access_decisions", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessGrantRecord", b =>
                {
                    b.Property<string>("SensitiveAccessRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrantDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumSuccessfulReads")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PolicyRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuccessfulReadCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("SensitiveAccessRequestId");

                    b.HasIndex("WorkspaceId", "PolicyRevision");

                    b.HasIndex("WorkspaceId", "OwnerUserId", "ExpiresAt");

                    b.ToTable("sensitive_access_grants", null, t =>
                        {
                            t.HasCheckConstraint("CK_sensitive_access_grants_grant_duration", "\"GrantDurationSeconds\" BETWEEN 60 AND 3600");

                            t.HasCheckConstraint("CK_sensitive_access_grants_maximum_successful_reads", "\"MaximumSuccessfulReads\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_sensitive_access_grants_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_sensitive_access_grants_policy_revision", "\"PolicyRevision\" > 0");

                            t.HasCheckConstraint("CK_sensitive_access_grants_successful_read_count", "\"SuccessfulReadCount\" >= 0 AND \"SuccessfulReadCount\" <= \"MaximumSuccessfulReads\"");

                            t.HasCheckConstraint("CK_sensitive_access_grants_time_window", "\"StartsAt\" < \"ExpiresAt\"");

                            t.HasCheckConstraint("CK_sensitive_access_grants_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessPolicyRevisionRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("GrantDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumSuccessfulReads")
                        .HasColumnType("integer");

                    b.Property<int>("RequestTimeoutSeconds")
                        .HasColumnType("integer");

                    b.HasKey("WorkspaceId", "Revision");

                    b.HasIndex("WorkspaceId", "CreatedAt");

                    b.ToTable("sensitive_access_policy_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_sensitive_access_policy_revisions_grant_duration", "\"GrantDurationSeconds\" BETWEEN 60 AND 3600");

                            t.HasCheckConstraint("CK_sensitive_access_policy_revisions_maximum_successful_reads", "\"MaximumSuccessfulReads\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_sensitive_access_policy_revisions_request_timeout", "\"RequestTimeoutSeconds\" BETWEEN 60 AND 3600");

                            t.HasCheckConstraint("CK_sensitive_access_policy_revisions_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_sensitive_access_policy_revisions_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PolicyRevision")
                        .HasColumnType("integer");

                    b.Property<string>("RedactedSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RequestReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RequestTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SensitiveRecordReferenceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("SensitiveRecordReferenceId");

                    b.HasIndex("WorkspaceId", "PolicyRevision");

                    b.HasIndex("Status", "ExpiresAt", "UpdatedAt");

                    b.HasIndex("WorkspaceId", "Status", "UpdatedAt");

                    b.ToTable("sensitive_access_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_sensitive_access_requests_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_sensitive_access_requests_policy_revision", "\"PolicyRevision\" > 0");

                            t.HasCheckConstraint("CK_sensitive_access_requests_request_timeout", "\"RequestTimeoutSeconds\" BETWEEN 60 AND 3600");

                            t.HasCheckConstraint("CK_sensitive_access_requests_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveMemoryPayloadRecord", b =>
                {
                    b.Property<string>("MemoryItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ContractVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectionScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemoryItemId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("sensitive_memory_payloads", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveRecordReferenceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MemoryItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedactedSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ReferenceLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("MemoryItemId");

                    b.HasIndex("SourceEventId");

                    b.HasIndex("WorkspaceId", "ReceivedAt");

                    b.HasIndex("WorkspaceId", "OwnerUserId", "ExpiresAt");

                    b.ToTable("sensitive_record_references", null, t =>
                        {
                            t.HasCheckConstraint("CK_sensitive_record_references_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_sensitive_record_references_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SharedMemoryItemRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("AllowsAgentContext")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("CoreTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExternalPublicationDecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalPublicationDecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalPublicationState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("LocalOnly");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RetentionKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("SafeSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SearchTagKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("||");

                    b.Property<string>("SearchTerms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("||");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TaskKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string>("TopicTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("AllowsAgentContext", "Sensitivity", "Visibility", "ExpiresAt");

                    b.HasIndex("WorkspaceId", "ProjectKey", "TaskKey", "UpdatedAt");

                    b.HasIndex("RetentionKind", "ExternalPublicationState", "ExpiresAt", "CreatedAt", "Id")
                        .HasDatabaseName("IX_shared_memory_items_cleanup_candidates");

                    b.ToTable("shared_memory_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_shared_memory_items_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_shared_memory_items_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SourceEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "ReceivedAt");

                    b.ToTable("source_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_source_events_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_source_events_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.WikiProposalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("AllowsAgentContext")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("CoreTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SafeSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SearchTagKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("||");

                    b.Property<string>("SearchTerms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("||");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TaskKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string>("TopicTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.HasIndex("AllowsAgentContext", "Sensitivity", "CreatedAt");

                    b.HasIndex("WorkspaceId", "ProjectKey", "TaskKey", "CreatedAt");

                    b.ToTable("wiki_proposals", null, t =>
                        {
                            t.HasCheckConstraint("CK_wiki_proposals_owner_user_id", "\"OwnerUserId\" <> ''");

                            t.HasCheckConstraint("CK_wiki_proposals_workspace_id", "\"WorkspaceId\" <> ''");
                        });
                });

            modelBuilder.Entity("Luthn.Core.Persistence.ClassificationResultRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEvent");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.CollectionProvenanceRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SharedMemoryItemRecord", null)
                        .WithOne()
                        .HasForeignKey("Luthn.Core.Persistence.CollectionProvenanceRecord", "MemoryItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", null)
                        .WithOne()
                        .HasForeignKey("Luthn.Core.Persistence.CollectionProvenanceRecord", "SourceEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessDecisionRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SensitiveAccessRequestRecord", "SensitiveAccessRequest")
                        .WithMany()
                        .HasForeignKey("SensitiveAccessRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SensitiveAccessRequest");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessGrantRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SensitiveAccessRequestRecord", "SensitiveAccessRequest")
                        .WithOne("Grant")
                        .HasForeignKey("Luthn.Core.Persistence.SensitiveAccessGrantRecord", "SensitiveAccessRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Luthn.Core.Persistence.SensitiveAccessPolicyRevisionRecord", "Policy")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PolicyRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("SensitiveAccessRequest");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessRequestRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SensitiveRecordReferenceRecord", "SensitiveRecordReference")
                        .WithMany()
                        .HasForeignKey("SensitiveRecordReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Luthn.Core.Persistence.SensitiveAccessPolicyRevisionRecord", "Policy")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PolicyRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("SensitiveRecordReference");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveMemoryPayloadRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SharedMemoryItemRecord", null)
                        .WithOne()
                        .HasForeignKey("Luthn.Core.Persistence.SensitiveMemoryPayloadRecord", "MemoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveRecordReferenceRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SharedMemoryItemRecord", "MemoryItem")
                        .WithMany()
                        .HasForeignKey("MemoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemoryItem");

                    b.Navigation("SourceEvent");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.WikiProposalRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEvent");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveAccessRequestRecord", b =>
                {
                    b.Navigation("Grant");
                });
#pragma warning restore 612, 618
        }
    }
}
