// <auto-generated />
using System;
using Luthn.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luthn.Core.Persistence.Persistence.Migrations
{
    [DbContext(typeof(LuthnDbContext))]
    [Migration("20260703000455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Luthn.Core.Persistence.AuditEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RedactionState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.ClassificationResultRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StorageDecision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.ToTable("classification_results", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveRecordReferenceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.ToTable("sensitive_record_references", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SourceEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ContainsSensitiveMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("source_events", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.WikiProposalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("AllowsAgentContext")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("CoreTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.ToTable("wiki_proposals", (string)null);
                });

            modelBuilder.Entity("Luthn.Core.Persistence.ClassificationResultRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEvent");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.SensitiveRecordReferenceRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEvent");
                });

            modelBuilder.Entity("Luthn.Core.Persistence.WikiProposalRecord", b =>
                {
                    b.HasOne("Luthn.Core.Persistence.SourceEventRecord", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
